[package]
name = "phantom-database"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
tokio-postgres = { workspace = true }
tracing = { workspace = true }
dotenv = { workspace = true }
chrono = { workspace = true }
phantom-types = { workspace = true }
serde_json = { workspace = true }
