[package]
name = "flux-main"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
dotenv = { workspace = true }
flux-database = { workspace = true }
flux-http = { workspace = true }
flux-smtp = { path = "../smtp" }
flux-types = { workspace = true }
