[package]
name = "flux-http"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
tracing = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
axum = { workspace = true }
chrono = { workspace = true }
rand = { workspace = true }
flux-types = { workspace = true }
flux-database = { workspace = true }
